version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23.5
    commands:
    - yum install -y zip
  build:
    commands:
    - cd lambdas # we need to be in the lambdas directory
    - | # we just use this to allow multiline command formatting for easier readability
      for dir in */ ; do
        dirname=${dir%/};
        cd "$dirname";
        GOOS=linux GOARCH=amd64 go build -mod=readonly -o bootstrap main.go || { echo "Bootstrap failed"; exit 1; };
        if [ ! -f "bootstrap" ]; then
          echo "Error: Bootstrap not created in $dirname";
          exit 1;
        fi
        chmod +x bootstrap;
        zip -j "../${dirname}.zip" bootstrap;
        cd ..
        aws lambda update-function-code \
          --function-name "arora-search-${dirname}" \
          --zip-file "fileb://${dirname}.zip" || { echo "Function code update failed"; exit 1; }
        version=$(aws lambda publish-version \
          --function-name "arora-search-${dirname}" \
          --description "PROD Release" | jq -r '.Version') || { echo "Version publish failed"; exit 1; }
        aws lambda update-alias \
          --function-name "arora-search-${dirname}" \
          --name PROD \
          --function-version "$version" \
          --description "PROD Release" || \
        aws lambda create-alias \
          --function-name "arora-search-${dirname}" \
          --name PROD \
          --function-version "$version" \
          --description "PROD Release" || { echo "Alias update/create failed"; exit 1; }
      done
    # the previous code does the following:
    # 1. loop through the directories in the lambdas directory
    # 2. set the directory name to the name of the current directory
    # 3. cd into the directory we are working with
    # 4. build the go binary as "bootstrap" (needed for lambda execution) (if this fails then exit)
    # 5. check if the bootstrap file exists, if not then log and fail
    # 6. make the bootstrap executable
    # 7. zip the bootstrap file (this is what we send to the lambda function)
    # 8. cd out of the directory we just worked with
    # 9. deploy the new function code to lambda and publish it as a new version
