GET https://r8oxhje7na.execute-api.us-east-1.amazonaws.com/dev/search/finger
Content-Type: application/json

{
    "maxID": 7000000000,
    "searchCriteria": {
        "visits": 0
    }
}


###


POST https://r8oxhje7na.execute-api.us-east-1.amazonaws.com/dev/search/brain
Content-Type: application/json

{
    "numGames": 5,
    "searchCriteria": {
        "visits": 1
    }
}
